### ISSUE TITLE
Need graps config file

### ISSUE THREAD

**Issue by ltaoist** [davetcoleman/clam#5]
`grasp_data_.loadRobotGraspData` has not been called. The old `loadRobotGraspData` has been remove in commit https://github.com/davetcoleman/clam/commit/c341a813d55e9af8cc53a72b11e71bbb3f4b702e, but no new one added.

From the example in https://github.com/davetcoleman/moveit_simple_grasps/blob/b8eef918d842309d84c028065a5fa0476a88848a/src/simple_grasps_test.cpp line `92` and https://github.com/davetcoleman/moveit_simple_grasps/blob/b8eef918d842309d84c028065a5fa0476a88848a/config/baxter_grasp_data.yaml, does that it need a end_effector yaml config file and run the script by roslaunch and load such yaml as param ?

**Comment by ltaoist** [comment]
I try add a new yaml file from the old file and the example:

``` yaml
base_link: 'base_link'

gripper_group:
  end_effector_name: 'gripper_group'
  joints : ['gripper_finger_joint']
  pregrasp_posture : [0.0]
  grasp_posture : [1.0]
  end_effector_parent_link : 'gripper_roll_link'
  pregrasp_time_from_start : 4.0
  grasp_time_from_start : 4.0
  grasp_pose_to_eef : [0,0,0]    // What should this would be ?
```

and add this line in 'simple_pick_place.cpp'

``` cpp
  if(!grasp_data_.loadRobotGraspData(nh, EE_GROUP))
  {
      ROS_ERROR_STREAM_NAMED("simple_pick_place", "Cannot load end_effector");
      return 1;
  }
  // ---------------------------------------------------------------------------------------------
  // Load grasp generator
  moveit_simple_grasps_.reset(new moveit_simple_grasps::SimpleGrasps(rviz_tools_));
```

and the launch file : 

``` xml
<launch>

  <arg name="debug" default="true"/>
  <rosparam command="load" file="$(find clam_pick_place)/config/clam_grasp_data.yaml"/>

  <group>
    <node name="$(anon simple_pick_place)" type="simple_pick_place" pkg="clam_pick_place">
    </node>   
  </group>

</launch>
```

 and it work ! (but not look correct) . I think it because the grasp_pose_to_eef is not right ...
