### ISSUE TITLE
No "loadRobotGraspData" called in "simple pick place" demo hydro

### ISSUE THREAD

**Issue by ltaoist** [davetcoleman/clam#6]
Hi Dave,

I am running movit and pick_place on ROS Hydro. 

Currently, when Itry to run the pick and place demo, I get an error message stating "no motion planning found". 

When I compare the `clam_pick_place/src/simple_pick_place.cpp` in hydro and groovy, I saw that  the "loadRobotGraspData" function is not called in the hydro version. 

For this reason, `grasp_data_` is not initialized and then pick or place cannot compute any motion plan. I saw that for the Hydro version, you deleted this call in the following commit: https://github.com/davetcoleman/clam/commit/c341a813d55e9af8cc53a72b11e71bbb3f4b702e)

I also found that in hydro, `loadRobotGraspData` became a part of the moveit API and it is now  a method of `grasp_data_` . 

It seems the functionality is the same as in Groovy. Except that in Hydro, the grasp data values are assigned through a yaml file while in groovy they are assigned within the code. 

I tried to fix this. So I modified simple_pick_place.cpp by adding `grasp_data_. loadRobotGraspData(nh, EE_GROUP)` before the line `moveit_simple_grasps_.reset`. I also added a config file like the following one: [reem_grasp_data.yaml](https://github.com/davetcoleman/moveit_simple_grasps/blob/b8eef918d842309d84c028065a5fa0476a88848a/config/reem_grasp_data.yaml) and [baxter_grasp_data.yaml](https://github.com/davetcoleman/moveit_simple_grasps/blob/b8eef918d842309d84c028065a5fa0476a88848a/config/baxter_grasp_data.yaml) and finally loaded through roslaunch. 

My code currently works, but the blocks are picked up by the wrist. I think the clam gripper posture is incorrect. I think the error maybe in my config file. 

Here are my changes to "simple_pick_place.cpp" : 

``` cpp
  if(!grasp_data_.loadRobotGraspData(nh, EE_GROUP))
  {
      ROS_ERROR_STREAM_NAMED("simple_pick_place", "Cannot load end_effector");
      return 1;
  }
  // ---------------------------------------------------------------------------------------------
  // Load grasp generator
  moveit_simple_grasps_.reset(new moveit_simple_grasps::SimpleGrasps(rviz_tools_));
```

And here is my launch file: 

``` xml
<launch>

  <arg name="debug" default="true"/>
  <rosparam command="load" file="$(find clam_pick_place)/config/clam_grasp_data.yaml"/>

  <group>
    <node name="$(anon simple_pick_place)" type="simple_pick_place" pkg="clam_pick_place">
    </node>   
  </group>

</launch>
```

And here is the yaml file : 

``` yaml
base_link: 'base_link'

gripper_group:
  end_effector_name: 'gripper_group'
  joints : ['gripper_finger_joint']
  pregrasp_posture : [0.0]
  grasp_posture : [1.0]
  end_effector_parent_link : 'gripper_roll_link'
  // what should the following be ?
  pregrasp_time_from_start : 4.0
  grasp_time_from_start : 4.0
  grasp_pose_to_eef : [0,0,0]
```

I would appreciate any feedback on this. We almost got this working!
